name: Greeting data academy

on:
  push:
    branches:
      - main  

env:
  DAY_OF_WEEK: 2a
  MY_USERNAME: ${{ github.actor }}
  DIRECTORY: 02_devops_fundamentals/ci_cd/terraform-exercise-3a
  REQUIREMENTS: 02_devops_fundamentals/ci_cd/terraform-exercise-3a/unittests/requirements.txt
  TESTDIR: 02_devops_fundamentals/ci_cd/terraform-exercise-3a/unittests
  $FAIL: true 

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 7th edition, this is $WEEKDAY 's first exercise! I'm  $MY_USERNAME !'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise!"
        env:
          ACADEMY_TYPE: Data
          MY_NAME: Rafa
          WEEKDAY: Monday 

  checkov:
    runs-on: self-hosted
    # needs: greeting_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Checkov GitHub Action
       # uses: bridgecrewio/checkov-action@v12
        #with:
         # directory: terraform/terraform-exercise-3a
          #soft_fail: true

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d $DIRECTORY --soft-fail
  pytest:
    runs-on: self-hosted
    #needs: checkov
    
    strategy:
      matrix:
        python-version: [3.12.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r $REQUIREMENTS  # Adjust according to your project setup

      - name: Run Pytest
        run: pytest -d $TESTDIR




