name: Greeting data academy

on:
  push:
    branches:
      - main  

env:
  DAY_OF_WEEK: 2a
  MY_USERNAME: ${{ github.actor }}

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 7th edition, this is $WEEKDAY 's first exercise! I'm  $MY_USERNAME !'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise!"
        env:
          ACADEMY_TYPE: Data
          MY_NAME: Rafaecho "6362646b67613c6981db76f4d25e68e463a9af2cc8d16e31bfeabe39153606a0  actions-runner-linux-x64-2.315.0.tar.gz" | shasum -a 256 -c
          WEEKDAY: Monday 

    week_job:
      runs-on: self-hosted
      needs: greeting_job
      env:
        GREETING: hello
      steps:
        - name: "Say 'Hello Data Academy 7th edition, this is $WEEKDAY 's first exercise! I'm  $MY_USERNAME !'"
          run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise!"
          env:
            ACADEMY_TYPE: Data
            MY_NAME: Rafaecho "6362646b67613c6981db76f4d25e68e463a9af2cc8d16e31bfeabe39153606a0  actions-runner-linux-x64-2.315.0.tar.gz" | shasum -a 256 -c
            WEEKDAY: Monday 



