name: Greeting data academy

on:
  push:
    branches:
      - main  

env:
  DAY_OF_WEEK: 2a
  MY_USERNAME: ${{ github.actor }}
  DIRECTORY: 02_devops_fundamentals/ci_cd/terraform-exercise-3a
  $FAIL: true 

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 7th edition, this is $WEEKDAY 's first exercise! I'm  $MY_USERNAME !'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise!"
        env:
          ACADEMY_TYPE: Data
          MY_NAME: Rafaecho "6362646b67613c6981db76f4d25e68e463a9af2cc8d16e31bfeabe39153606a0  actions-runner-linux-x64-2.315.0.tar.gz" | shasum -a 256 -c
          WEEKDAY: Monday 

  checkov:
    runs-on: self-hosted
    needs: greeting_job
    env:
      GREETING: hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: test/console,results.sarif
          directory: $DIRECTORY
          soft-fail: $FAIL

      #- name: Run Checkov
      #  run: checkov -d $DIRECTORY --soft-fail

        env:
          ACADEMY_TYPE: Data
          MY_NAME: Rafaecho "6362646b67613c6981db76f4d25e68e463a9af2cc8d16e31bfeabe39153606a0  actions-runner-linux-x64-2.315.0.tar.gz" | shasum -a 256 -c
          WEEKDAY: Monday 




